mcq/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:student_id>/quiz/', views.quiz, name='quiz'),
    path('<int:student_id>/quiz/quiz-log/', views.quiz_log, name='quiz_log'),
    path('<int:student_id>/quiz/G3-choice/', views.g3_choice, name='g3_choice'),
    path('<int:student_id>/subimt_quiz/', views.submit_quiz, name='submit_quiz'),
    path('<int:student_id>/survey/', views.survey, name='survey'),
    path('<int:student_id>/submit_survey/', views.submit_survey, name='submit_survey'),
    path('<int:student_id>/results/', views.results, name='results'),
]

polls/models.py
import datetime
import random

from django.db import models
from django.utils import timezone

# Create your models here.
class Base_Question(models.Model):
    question_text = models.CharField(max_length=2000)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    def __str__(self):
        return self.question_text
    # def was_published_recently(self):
    #     now = timezone.now()
    #     return now - datetime.timedelta(days=1) <= self.pub_date <= now

    class Meta:
        abstract = True


class Base_Choice(models.Model):
    choice_text = models.CharField(max_length=2000)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text

    class Meta:
        abstract = True


######## INSTRUCTOR QUESTIONS ########


class Question(Base_Question):
    TYPE1 = 'T1'
    TYPE2 = 'T2'
    QUESTION_TYPE_CHOICES = [
        (TYPE1, 'For all students'),
        (TYPE2, 'For students not creating a question'),
    ]
    question_type = models.CharField(
        max_length=2,
        choices=QUESTION_TYPE_CHOICES,
        default=TYPE1,
    )
    sort_order = models.IntegerField(default=0)


class Choice(Base_Choice):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)


class Survey_Question(Base_Question):
    TYPE1 = 'T1'
    TYPE2 = 'T2'
    TYPE3 = 'T3'
    TYPE4 = 'T4'
    QUESTION_TYPE_CHOICES = [
        (TYPE1, 'For groups 1, 2, 4 and 5'),
        (TYPE2, 'For groups 2, 4 and 5'),
        (TYPE3, 'For group 4'),
        (TYPE4, 'For group 5'),
    ]
    question_type = models.CharField(
        max_length=2,
        choices=QUESTION_TYPE_CHOICES,
        default=TYPE1,
    )
    sort_order = models.IntegerField(default=0)


######## STUDENT QUESTIONS ########


class Student(models.Model):
    GROUP1 = 'G1'
    GROUP2 = 'G2'
    GROUP3 = 'G3'
    GROUP4 = 'G4'
    GROUP5 = 'G5'
    GROUP_TYPE_CHOICES = [
        (GROUP1, 'Control group'),
        (GROUP2, 'Experimental group without choice'),
        (GROUP3, 'Experimental group with choice'),
        (GROUP4, 'Group 3 choosing not to create MCQ'),
        (GROUP5, 'Group 3 choosing to create MCQ'),
    ]
    STAGE1 = 'S1'
    STAGE2 = 'S2'
    STAGE3 = 'S3'
    STAGE_CHOICES = [
        (STAGE1, 'Quiz'),
        (STAGE2, 'Survey'),
        (STAGE3, 'Results'),
    ]
    name = models.CharField(max_length=200, unique=True)
    stage = models.CharField(
        max_length=2,
        choices=STAGE_CHOICES,
        default='S1',
    )
    group = models.CharField(
        max_length=2,
        choices=GROUP_TYPE_CHOICES,
        default='G1',
    )
    consent_create_mcq = models.BooleanField(default=False)
    consent_survey = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Student_Question(Base_Question):
    explanation_text = models.CharField(max_length=2000)
    topics = models.CharField(max_length=1000, default="")
    by_student = models.OneToOneField(
        Student,
        on_delete=models.CASCADE,
        related_name='creator_of',
    )


class Student_Question_Topic(models.Model):
    text = models.CharField(max_length=100)

    def __str__(self):
        return self.text


class Student_Choice(Base_Choice):
    question = models.ForeignKey(Student_Question, on_delete=models.CASCADE)


class Student_Response(models.Model):
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_id = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.student_id) + ' : ' + str(self.question_id) + ' - ' + str(self.choice_id)


class Student_Survey_Response(models.Model):
    CHOICE1 = 'C1'
    CHOICE2 = 'C2'
    CHOICE3 = 'C3'
    CHOICE4 = 'C4'
    CHOICE5 = 'C5'
    CHOICE_TYPE_CHOICES = [
        (CHOICE1, 'Strongly disagree'),
        (CHOICE2, 'Somewhat disagree'),
        (CHOICE3, 'Neither agree nor disagree'),
        (CHOICE4, 'Somewhat agree'),
        (CHOICE5, 'Strongly agree'),
    ]
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    survey_question_id = models.ForeignKey(Survey_Question, on_delete=models.CASCADE)
    survey_choice_id = models.CharField(
        max_length=2,
        choices=CHOICE_TYPE_CHOICES,
        default='C1',
    )

    def __str__(self):
        return str(self.student_id) + ' : ' + str(self.survey_question_id) + ' - ' + str(self.survey_choice_id)


class Student_Survey_Additional_Text(models.Model):
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    text = models.CharField(max_length=2000)

    def __str__(self):
        return str(self.student_id) + ' : ' + self.text

class Log(models.Model):
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    element_type = models.CharField(max_length=100)
    action = models.CharField(max_length=100)
    element_id = models.CharField(max_length=100)
    client_timestamp = models.CharField(max_length=100, default="")
    def __str__(self):
        return str(self.student_id) + ' : ' + str(self.action) + ' ' + str(self.element_type) + ' ' + str(self.element_id)

polls/forms.py
from django import forms
from .models import Student

class LoginForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name']

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.db.models import F, Q
from django.views import generic
from django.utils import timezone
from django.views.decorators.http import require_http_methods, require_POST

import random
import codecs
import json
import logging
import os

from .models import *
# from .models import Question, Choice, Student, Student_Choice, Student_Question, Student_Response, Survey_Choice, Survey_Question
from .forms import LoginForm 


@require_http_methods(['GET', 'POST'])
def index(request):
    if request.method == 'GET':
        f = LoginForm()
    else:
        f = LoginForm(request.POST)
        if f.is_valid():
            student = f.save()
            if student.name.startswith('1'):
                student.group = Student.GROUP1
            elif student.name.startswith('2'):
                student.group = Student.GROUP2
            elif student.name.startswith('3'):
                student.group = Student.GROUP3
            else:
                student.group = random.choice(
                [Student.GROUP1, Student.GROUP2, Student.GROUP3])
            student.stage = Student.STAGE1
            student.save()
            return HttpResponseRedirect(reverse('polls:quiz', args=(student.id,)))
    print(render(request, 'polls/STAGE0/login_form.html', {'form': f}))
    return render(request, 'polls/STAGE0/login_form.html', {'form': f})


def quiz(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    if student.stage == Student.STAGE2:
        return HttpResponseRedirect(reverse('polls:survey', args=(student.id,)))
    elif student.stage == Student.STAGE3:
        return HttpResponseRedirect(reverse('polls:results', args=(student.id,)))
    latest_question_list = Question.objects.filter(
        question_type=Question.TYPE1)
    topics = Student_Question_Topic.objects.none()
    if student.group == Student.GROUP1 or student.group == Student.GROUP4:
        latest_question_list = latest_question_list.union(
            Question.objects.filter(question_type=Question.TYPE2))
    elif student.group == Student.GROUP2 or student.group == Student.GROUP5:
        topics = Student_Question_Topic.objects.all()
    context = {'latest_question_list': latest_question_list.order_by(
        'sort_order'), 'student': student, 'topics':topics}
    return render(request, 'polls/STAGE1/quiz_dynamic_individual.html', context)


@require_POST
def quiz_log(request, student_id):
    now = timezone.now()
    date = now.date()
    student = get_object_or_404(Student, pk=student_id)
    element_type = request.POST.get('type')
    action = request.POST.get('action')
    element_id = request.POST.get('element_id')
    client_timestamp = request.POST.get('timestamp', "")
    if element_type == 'choice':
        choice_id = element_id.split(',')[1]
        choice = get_object_or_404(Choice, pk=choice_id)
        append = "correct" if choice.is_correct else "incorrect"
        action = action + " " + append
    try:
        # log = Log(student_id=student, element_type=element_type,
        #           action=action, element_id=element_id, client_timestamp=client_timestamp)
        # log.save()
        log_dict = {
            'student_id': str(student),
            'element_type': element_type,
            'action': action,
            'element_id': element_id,
            'client_timestamp': client_timestamp,
            'server_timestamp': str(now)
        }
        log_str = json.dumps(log_dict)
        filename = "./student_response_log/"+str(date)+".txt"
        os.makedirs(os.path.dirname(filename), exist_ok=True)
        with open(filename, "a") as f:
            f.write(log_str)
            f.write('\n')
    except Exception:
        pass
    return HttpResponse(
        json.dumps({}),
        content_type="application/json"
    )

@require_POST
def g3_choice(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    response_data = {}
    latest_question_list = Question.objects.none()
    form = ''
    choice = request.POST.get('choice')
    if student.group == Student.GROUP3:
        if choice == Student.GROUP4:
            student.group = Student.GROUP4
            latest_question_list = Question.objects.filter(
                question_type=Question.TYPE2)
        else:
            student.group = Student.GROUP5
            form = loader.render_to_string('polls/STAGE1/create_mcq_form_wrapper.html',
                {'topics':Student_Question_Topic.objects.all()})
        student.save()
    submit = loader.render_to_string(
        'polls/STAGE1/submit-quiz-button.html', {})

    response_data['append_question_list'] = loader.render_to_string(
    'polls/STAGE1/list_questions_individual.html',
    {'latest_question_list': latest_question_list.order_by('sort_order'), 'offset': 6})
    response_data['create_mcq_form'] = form
    response_data['submit'] = submit

    return HttpResponse(
        json.dumps(response_data),
        content_type="application/json"
    )


def survey(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    if student.stage == Student.STAGE1:
        return HttpResponseRedirect(reverse('polls:quiz', args=(student.id,)))
    elif student.stage == Student.STAGE3:
        return HttpResponseRedirect(reverse('polls:results', args=(student.id,)))
    context = {'student': student}
    survey_question_list = Survey_Question.objects.filter(
        question_type=Survey_Question.TYPE1)
    if student.group != Student.GROUP1:
        survey_question_list = survey_question_list.union(
            Survey_Question.objects.filter(question_type=Survey_Question.TYPE2))
    if student.group == Student.GROUP4:
        context['extra_question_list'] = Survey_Question.objects.filter(
            question_type=Survey_Question.TYPE3).order_by('sort_order')
    if student.group == Student.GROUP5:
        context['extra_question_list'] = Survey_Question.objects.filter(
            question_type=Survey_Question.TYPE4).order_by('sort_order')
    context['survey_question_list'] = survey_question_list.order_by(
        'sort_order')
    return render(request, 'polls/STAGE2/survey.html', context)


@require_POST
def submit_survey(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    if student.stage == Student.STAGE1:
        return HttpResponseRedirect(reverse('polls:quiz', args=(student.id,)))
    elif student.stage == Student.STAGE3:
        return HttpResponseRedirect(reverse('polls:results', args=(student.id,)))
    else:
        choice_map = {
            'CHOICE1': Student_Survey_Response.CHOICE1,
            'CHOICE2': Student_Survey_Response.CHOICE2,
            'CHOICE3': Student_Survey_Response.CHOICE3,
            'CHOICE4': Student_Survey_Response.CHOICE4,
            'CHOICE5': Student_Survey_Response.CHOICE5
        }
        for key, value in request.POST.items():
            if key.startswith('survey_'):
                question_id = int(value.split(',')[0])
                survey_choice = value.split(',')[1]
                survey_choice_id = choice_map[survey_choice]
                survey_question = Survey_Question.objects.get(id=question_id)
                try:
                    student_survey_response = Student_Survey_Response(
                        student_id=student, survey_question_id=survey_question, survey_choice_id=survey_choice_id)
                    student_survey_response.save()
                except Exception:
                    logging.error("Could not save survey response for "+student)
        consent_survey = request.POST.get('consent_survey') == "True"
        choice_text = request.POST.get('choice_text', '')
        if choice_text:
            try:
                addn_text = Student_Survey_Additional_Text(student_id = student, text = choice_text)
                addn_text.save()
            except Exception:
                    logging.error("Could not save survey response additional text for "+student)
        student.consent_survey = consent_survey
        student.stage = Student.STAGE3
        student.save()
        return HttpResponseRedirect(reverse('polls:results', args=(student.id,)))


def results(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    if student.stage == Student.STAGE1:
        return HttpResponseRedirect(reverse('polls:quiz', args=(student.id,)))
    elif student.stage == Student.STAGE2:
        return HttpResponseRedirect(reverse('polls:survey', args=(student.id,)))
    responses = Student_Response.objects.filter(student_id=student)
    score = 0
    total = 0
    for response in responses:
        total += 1
        if response.choice_id.is_correct:
            score += 1
    context = {'student': student, 'score': str(score), 'total': str(total)}
    print(context)
    return render(request, 'polls/STAGE3/results.html', context)


@require_POST
def submit_quiz(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    if student.stage == Student.STAGE2:
        return HttpResponseRedirect(reverse('polls:survey', args=(student.id,)))
    elif student.stage == Student.STAGE3:
        return HttpResponseRedirect(reverse('polls:results', args=(student.id,)))
    else:
        for key, value in request.POST.items():
            if key.startswith('mcq_'):
                question_id = int(value.split(',')[0])
                choice_id = int(value.split(',')[1])
                question = Question.objects.get(id=question_id)
                choice_filter = Choice.objects.filter(question=question, id=choice_id)
                try:
                    choice = choice_filter[0]
                    student_response = Student_Response(student_id=student, question_id=question, choice_id=choice)
                    student_response.save()

polls/templates/polls/STAGE2/list_questions.html
{% for question in questions_to_list %}
<div class="collection-item grey lighten-5 row">
    <span class="col s12 m7">{{ question.question_text|safe }}</span>
    <p>
        <label class="col s12 m1">
            <input type="radio" name="survey_{{ question.id }}" value="{{ question.id }},CHOICE1"
                class="with-gap umblue" required>
            <span>
                <span class="black-text hide-on-small-only"></span>
                <span class="black-text hide-on-med-and-up">Strongly disagree</span>
            </span>
        </label>
    </p>

    <p>
        <label class="col s12 m1">
            <input type="radio" name="survey_{{ question.id }}" value="{{ question.id }},CHOICE2"
                class="with-gap umblue" required>
            <span>
                <span class="black-text hide-on-small-only"></span>
                <span class="black-text hide-on-med-and-up">Somewhat disagree</span>
            </span>
        </label>
    </p>

    <p>
        <label class="col s12 m1">
            <input type="radio" name="survey_{{ question.id }}" value="{{ question.id }},CHOICE3"
                class="with-gap umblue" required>
            <span>
                <span class="black-text hide-on-small-only"></span>
                <span class="black-text hide-on-med-and-up">Neither agree nor disagree</span>
            </span>
        </label>
    </p>

    <p>
        <label class="col s12 m1">
            <input type="radio" name="survey_{{ question.id }}" value="{{ question.id }},CHOICE4"
                class="with-gap umblue" required>
            <span>
                <span class="black-text hide-on-small-only"></span>
                <span class="black-text hide-on-med-and-up">Somewhat agree</span>
            </span>
        </label>
    </p>

    <p>
        <label class="col s12 m1">
            <input type="radio" name="survey_{{ question.id }}" value="{{ question.id }},CHOICE5"
                class="with-gap umblue" required>
            <span>
                <span class="black-text hide-on-small-only"></span>
                <span class="black-text hide-on-med-and-up">Strongly agree</span>
            </span>
        </label>
    </p>
</div>
{% endfor %}

polls/templates/polls/STAGE2/survey.html
{% extends '../base.html' %}
{% load static %}
{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


{% if survey_question_list %}
    <p class="row">
        <span class="col s12">
            Hello {{ student.name }}! Your responses have been recorded! Your grades will soon reflect on your profile.
        </span>
        <span class="col s12">
            Please answer the following survey questions to help us improve the design and content of MOOC assessments.
            The survey will not take more than 5 minutes. Thank you in advance for your time!
        </span>
    </p>

    <p class="row">
        <span class="col s12">
            <strong>Please indicate how true each of the following statements is for you, on a scale of (1) “strongly
                disagree” to (5) “strongly agree” </strong>
        </span>
    </p>

    <form action="{% url 'polls:submit_survey' student.id %}" method="post" class="row" id="main-survey">
        {% csrf_token %}
        <div class="collection">
            <div class="collection-item grey lighten-5 hide-on-small-only row">
                <span class="black-text col m1 offset-m7">Strongly disagree</span>
                <span class="black-text col m1">Somewhat disagree</span>
                <span class="black-text col m1">Neither agree nor disagree</span>
                <span class="black-text col m1">Somewhat agree</span>
                <span class="black-text col m1">Strongly agree</span>
            </div>
            {% include "polls/STAGE2/list_questions.html" with questions_to_list=survey_question_list only %}
        </div>

        {% if student.group == 'G4' and extra_question_list %}
        <p class="row">
            <strong>“I chose to answer 4 additional questions rather than create an MCQ because:”</strong>
        </p>
        <div class="collection">
            <!-- <p class="collection-item grey lighten-5 hide-on-med-and-up row"> -->
            <p class="collection-item grey lighten-5 row">
                <strong>“I chose to answer 4 additional questions rather than create an MCQ because:”</strong>
            </p>
            <div class="collection-item grey lighten-5 hide-on-small-only row">
                <span class="black-text col m7"><strong>“I chose to answer 4 additional questions rather than
                        create an MCQ because:”</strong></span>
                <span class="black-text col m1">Strongly disagree</span>
                <span class="black-text col m1">Somewhat disagree</span>
                <span class="black-text col m1">Neither agree nor disagree</span>
                <span class="black-text col m1">Somewhat agree</span>
                <span class="black-text col m1">Strongly agree</span>
            </div>
            {% include "polls/STAGE2/list_questions.html" with questions_to_list=extra_question_list only %}
            <div class="collection-item grey lighten-5 row">
                <div class="input-field col s12">
                    <textarea class="materialize-textarea" name="choice_text"></textarea>
                    <label for="choice_text" class="black-text">Are there any other reasons behind your choice
                        to not create an MCQ? If yes, please explain as elaborately as possible.</label>
                </div>
            </div>
        </div>

        {% elif student.group == 'G5' and extra_question_list %}
        <p class="row">
            <strong>“I chose to create an MCQ rather than answer 4 additional questions because:”</strong>
        </p>
        <div class="collection">
            <!-- <p class="collection-item grey lighten-5 hide-on-med-and-up row"> -->
            <p class="collection-item grey lighten-5 row">
                <strong>“I chose to create an MCQ rather than answer 4 additional questions because:”</strong>
            </p>
            <div class="collection-item grey lighten-5 hide-on-small-only row">
                <span class="black-text col m7"><strong>“I chose to create an MCQ rather than answer 4
                        additional questions because:”</strong></span>
                <span class="black-text col m1 offset-m7">Strongly disagree</span>
                <span class="black-text col m1">Somewhat disagree</span>
                <span class="black-text col m1">Neither agree nor disagree</span>
                <span class="black-text col m1">Somewhat agree</span>
                <span class="black-text col m1">Strongly agree</span>
            </div>
            {% include "polls/STAGE2/list_questions.html" with questions_to_list=extra_question_list only %}
            <div class="collection-item grey lighten-5 row">
                <div class="input-field col s12">
                    <textarea class="materialize-textarea" name="choice_text"></textarea>
                    <label for="choice_text" class="black-text">Are there any other reasons behind your choice
                        to create an MCQ? If yes, please explain as elaborately as possible.</label>
                </div>
            </div>
        </div>

        {% endif %}

        <div class="collection">
            <div class="collection-item grey lighten-5 row">
                <span class="col s12">Can we use your anonymized survey responses as part of a research study? Your
                    answer to this question will have no impact on your evaluation for this course.</span>
                <p>
                    <label class="col s12">
                        <input type="radio" name="consent_survey" value="True" class="with-gap umblue" required>
                        <span>
                            <span class="black-text">Yes</span>
                        </span>
                    </label>
                </p>
                <p>
                    <label class="col s12">
                        <input type="radio" name="consent_survey" value="False" class="with-gap umblue" required>
                        <span>
                            <span class="black-text">No</span>
                        </span>
                    </label>
                </p>
            </div>
        </div>
        <div id="submit-survey">
            <button class="btn waves-effect waves-light umblue" type="submit" name="action">Submit
                survey</button>
        </div>
    </form>
{% else %}
    <p class="flow-text">No survey is available.</p>
{% endif %}

{% endblock %}