mcq/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:student_id>/quiz/', views.quiz, name='quiz'),
    path('<int:student_id>/quiz/quiz-log/', views.quiz_log, name='quiz_log'),
    path('<int:student_id>/quiz/G3-choice/', views.g3_choice, name='g3_choice'),
    path('<int:student_id>/subimt_quiz/', views.submit_quiz, name='submit_quiz'),
    path('<int:student_id>/survey/', views.survey, name='survey'),
    path('<int:student_id>/submit_survey/', views.submit_survey, name='submit_survey'),
    path('<int:student_id>/results/', views.results, name='results'),
]

polls/models.py
import datetime
import random

from django.db import models
from django.utils import timezone

# Create your models here.
class Base_Question(models.Model):
    question_text = models.CharField(max_length=2000)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    def __str__(self):
        return self.question_text
    # def was_published_recently(self):
    #     now = timezone.now()
    #     return now - datetime.timedelta(days=1) <= self.pub_date <= now

    class Meta:
        abstract = True


class Base_Choice(models.Model):
    choice_text = models.CharField(max_length=2000)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text

    class Meta:
        abstract = True


######## INSTRUCTOR QUESTIONS ########


class Question(Base_Question):
    TYPE1 = 'T1'
    TYPE2 = 'T2'
    QUESTION_TYPE_CHOICES = [
        (TYPE1, 'For all students'),
        (TYPE2, 'For students not creating a question'),
    ]
    question_type = models.CharField(
        max_length=2,
        choices=QUESTION_TYPE_CHOICES,
        default=TYPE1,
    )
    sort_order = models.IntegerField(default=0)


class Choice(Base_Choice):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)


class Survey_Question(Base_Question):
    TYPE1 = 'T1'
    TYPE2 = 'T2'
    TYPE3 = 'T3'
    TYPE4 = 'T4'
    QUESTION_TYPE_CHOICES = [
        (TYPE1, 'For groups 1, 2, 4 and 5'),
        (TYPE2, 'For groups 2, 4 and 5'),
        (TYPE3, 'For group 4'),
        (TYPE4, 'For group 5'),
    ]
    question_type = models.CharField(
        max_length=2,
        choices=QUESTION_TYPE_CHOICES,
        default=TYPE1,
    )
    sort_order = models.IntegerField(default=0)


######## STUDENT QUESTIONS ########


class Student(models.Model):
    GROUP1 = 'G1'
    GROUP2 = 'G2'
    GROUP3 = 'G3'
    GROUP4 = 'G4'
    GROUP5 = 'G5'
    GROUP_TYPE_CHOICES = [
        (GROUP1, 'Control group'),
        (GROUP2, 'Experimental group without choice'),
        (GROUP3, 'Experimental group with choice'),
        (GROUP4, 'Group 3 choosing not to create MCQ'),
        (GROUP5, 'Group 3 choosing to create MCQ'),
    ]
    STAGE1 = 'S1'
    STAGE2 = 'S2'
    STAGE3 = 'S3'
    STAGE_CHOICES = [
        (STAGE1, 'Quiz'),
        (STAGE2, 'Survey'),
        (STAGE3, 'Results'),
    ]
    name = models.CharField(max_length=200, unique=True)
    stage = models.CharField(
        max_length=2,
        choices=STAGE_CHOICES,
        default='S1',
    )
    group = models.CharField(
        max_length=2,
        choices=GROUP_TYPE_CHOICES,
        default='G1',
    )
    consent_create_mcq = models.BooleanField(default=False)
    consent_survey = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Student_Question(Base_Question):
    explanation_text = models.CharField(max_length=2000)
    topics = models.CharField(max_length=1000, default="")
    by_student = models.OneToOneField(
        Student,
        on_delete=models.CASCADE,
        related_name='creator_of',
    )


class Student_Question_Topic(models.Model):
    text = models.CharField(max_length=100)

    def __str__(self):
        return self.text


class Student_Choice(Base_Choice):
    question = models.ForeignKey(Student_Question, on_delete=models.CASCADE)


class Student_Response(models.Model):
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_id = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.student_id) + ' : ' + str(self.question_id) + ' - ' + str(self.choice_id)


class Student_Survey_Response(models.Model):
    CHOICE1 = 'C1'
    CHOICE2 = 'C2'
    CHOICE3 = 'C3'
    CHOICE4 = 'C4'
    CHOICE5 = 'C5'
    CHOICE_TYPE_CHOICES = [
        (CHOICE1, 'Strongly disagree'),
        (CHOICE2, 'Somewhat disagree'),
        (CHOICE3, 'Neither agree nor disagree'),
        (CHOICE4, 'Somewhat agree'),
        (CHOICE5, 'Strongly agree'),
    ]
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    survey_question_id = models.ForeignKey(Survey_Question, on_delete=models.CASCADE)
    survey_choice_id = models.CharField(
        max_length=2,
        choices=CHOICE_TYPE_CHOICES,
        default='C1',
    )

    def __str__(self):
        return str(self.student_id) + ' : ' + str(self.survey_question_id) + ' - ' + str(self.survey_choice_id)


class Student_Survey_Additional_Text(models.Model):
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    text = models.CharField(max_length=2000)

    def __str__(self):
        return str(self.student_id) + ' : ' + self.text

class Log(models.Model):
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    element_type = models.CharField(max_length=100)
    action = models.CharField(max_length=100)
    element_id = models.CharField(max_length=100)
    client_timestamp = models.CharField(max_length=100, default="")
    def __str__(self):
        return str(self.student_id) + ' : ' + str(self.action) + ' ' + str(self.element_type) + ' ' + str(self.element_id)

polls/forms.py
from django import forms
from .models import Student

class LoginForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name']

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.db.models import F, Q
from django.views import generic
from django.utils import timezone
from django.views.decorators.http import require_http_methods, require_POST

import random
import codecs
import json
import logging
import os

from .models import *
# from .models import Question, Choice, Student, Student_Choice, Student_Question, Student_Response, Survey_Choice, Survey_Question
from .forms import LoginForm 


@require_http_methods(['GET', 'POST'])
def index(request):
    if request.method == 'GET':
        f = LoginForm()
    else:
        f = LoginForm(request.POST)
        if f.is_valid():
            student = f.save()
            if student.name.startswith('1'):
                student.group = Student.GROUP1
            elif student.name.startswith('2'):
                student.group = Student.GROUP2
            elif student.name.startswith('3'):
                student.group = Student.GROUP3
            else:
                student.group = random.choice(
                [Student.GROUP1, Student.GROUP2, Student.GROUP3])
            student.stage = Student.STAGE1
            student.save()
            return HttpResponseRedirect(reverse('polls:quiz', args=(student.id,)))
    print(render(request, 'polls/STAGE0/login_form.html', {'form': f}))
    return render(request, 'polls/STAGE0/login_form.html', {'form': f})


def quiz(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    if student.stage == Student.STAGE2:
        return HttpResponseRedirect(reverse('polls:survey', args=(student.id,)))
    elif student.stage == Student.STAGE3:
        return HttpResponseRedirect(reverse('polls:results', args=(student.id,)))
    latest_question_list = Question.objects.filter(
        question_type=Question.TYPE1)
    topics = Student_Question_Topic.objects.none()
    if student.group == Student.GROUP1 or student.group == Student.GROUP4:
        latest_question_list = latest_question_list.union(
            Question.objects.filter(question_type=Question.TYPE2))
    elif student.group == Student.GROUP2 or student.group == Student.GROUP5:
        topics = Student_Question_Topic.objects.all()
    context = {'latest_question_list': latest_question_list.order_by(
        'sort_order'), 'student': student, 'topics':topics}
    return render(request, 'polls/STAGE1/quiz_dynamic_individual.html', context)


@require_POST
def quiz_log(request, student_id):
    now = timezone.now()
    date = now.date()
    student = get_object_or_404(Student, pk=student_id)
    element_type = request.POST.get('type')
    action = request.POST.get('action')
    element_id = request.POST.get('element_id')
    client_timestamp = request.POST.get('timestamp', "")
    if element_type == 'choice':
        choice_id = element_id.split(',')[1]
        choice = get_object_or_404(Choice, pk=choice_id)
        append = "correct" if choice.is_correct else "incorrect"
        action = action + " " + append
    try:
        # log = Log(student_id=student, element_type=element_type,
        #           action=action, element_id=element_id, client_timestamp=client_timestamp)
        # log.save()
        log_dict = {
            'student_id': str(student),
            'element_type': element_type,
            'action': action,
            'element_id': element_id,
            'client_timestamp': client_timestamp,
            'server_timestamp': str(now)
        }
        log_str = json.dumps(log_dict)
        filename = "./student_response_log/"+str(date)+".txt"
        os.makedirs(os.path.dirname(filename), exist_ok=True)
        with open(filename, "a") as f:
            f.write(log_str)
            f.write('\n')
    except Exception:
        pass
    return HttpResponse(
        json.dumps({}),
        content_type="application/json"
    )

@require_POST
def g3_choice(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    response_data = {}
    latest_question_list = Question.objects.none()
    form = ''
    choice = request.POST.get('choice')
    if student.group == Student.GROUP3:
        if choice == Student.GROUP4:
            student.group = Student.GROUP4
            latest_question_list = Question.objects.filter(
                question_type=Question.TYPE2)
        else:
            student.group = Student.GROUP5
            form = loader.render_to_string('polls/STAGE1/create_mcq_form_wrapper.html',
                {'topics':Student_Question_Topic.objects.all()})
        student.save()
    submit = loader.render_to_string(
        'polls/STAGE1/submit-quiz-button.html', {})

    response_data['append_question_list'] = loader.render_to_string(
    'polls/STAGE1/list_questions_individual.html',
    {'latest_question_list': latest_question_list.order_by('sort_order'), 'offset': 6})
    response_data['create_mcq_form'] = form
    response_data['submit'] = submit

    return HttpResponse(
        json.dumps(response_data),
        content_type="application/json"
    )


def survey(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    if student.stage == Student.STAGE1:
        return HttpResponseRedirect(reverse('polls:quiz', args=(student.id,)))
    elif student.stage == Student.STAGE3:
        return HttpResponseRedirect(reverse('polls:results', args=(student.id,)))
    context = {'student': student}
    survey_question_list = Survey_Question.objects.filter(
        question_type=Survey_Question.TYPE1)
    if student.group != Student.GROUP1:
        survey_question_list = survey_question_list.union(
            Survey_Question.objects.filter(question_type=Survey_Question.TYPE2))
    if student.group == Student.GROUP4:
        context['extra_question_list'] = Survey_Question.objects.filter(
            question_type=Survey_Question.TYPE3).order_by('sort_order')
    if student.group == Student.GROUP5:
        context['extra_question_list'] = Survey_Question.objects.filter(
            question_type=Survey_Question.TYPE4).order_by('sort_order')
    context['survey_question_list'] = survey_question_list.order_by(
        'sort_order')
    return render(request, 'polls/STAGE2/survey.html', context)


@require_POST
def submit_survey(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    if student.stage == Student.STAGE1:
        return HttpResponseRedirect(reverse('polls:quiz', args=(student.id,)))
    elif student.stage == Student.STAGE3:
        return HttpResponseRedirect(reverse('polls:results', args=(student.id,)))
    else:
        choice_map = {
            'CHOICE1': Student_Survey_Response.CHOICE1,
            'CHOICE2': Student_Survey_Response.CHOICE2,
            'CHOICE3': Student_Survey_Response.CHOICE3,
            'CHOICE4': Student_Survey_Response.CHOICE4,
            'CHOICE5': Student_Survey_Response.CHOICE5
        }
        for key, value in request.POST.items():
            if key.startswith('survey_'):
                question_id = int(value.split(',')[0])
                survey_choice = value.split(',')[1]
                survey_choice_id = choice_map[survey_choice]
                survey_question = Survey_Question.objects.get(id=question_id)
                try:
                    student_survey_response = Student_Survey_Response(
                        student_id=student, survey_question_id=survey_question, survey_choice_id=survey_choice_id)
                    student_survey_response.save()
                except Exception:
                    logging.error("Could not save survey response for "+student)
        consent_survey = request.POST.get('consent_survey') == "True"
        choice_text = request.POST.get('choice_text', '')
        if choice_text:
            try:
                addn_text = Student_Survey_Additional_Text(student_id = student, text = choice_text)
                addn_text.save()
            except Exception:
                    logging.error("Could not save survey response additional text for "+student)
        student.consent_survey = consent_survey
        student.stage = Student.STAGE3
        student.save()
        return HttpResponseRedirect(reverse('polls:results', args=(student.id,)))


def results(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    if student.stage == Student.STAGE1:
        return HttpResponseRedirect(reverse('polls:quiz', args=(student.id,)))
    elif student.stage == Student.STAGE2:
        return HttpResponseRedirect(reverse('polls:survey', args=(student.id,)))
    responses = Student_Response.objects.filter(student_id=student)
    score = 0
    total = 0
    for response in responses:
        total += 1
        if response.choice_id.is_correct:
            score += 1
    context = {'student': student, 'score': str(score), 'total': str(total)}
    print(context)
    return render(request, 'polls/STAGE3/results.html', context)


@require_POST
def submit_quiz(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    if student.stage == Student.STAGE2:
        return HttpResponseRedirect(reverse('polls:survey', args=(student.id,)))
    elif student.stage == Student.STAGE3:
        return HttpResponseRedirect(reverse('polls:results', args=(student.id,)))
    else:
        for key, value in request.POST.items():
            if key.startswith('mcq_'):
                question_id = int(value.split(',')[0])
                choice_id = int(value.split(',')[1])
                question = Question.objects.get(id=question_id)
                choice_filter = Choice.objects.filter(question=question, id=choice_id)
                try:
                    choice = choice_filter[0]
                    student_response = Student_Response(student_id=student, question_id=question, choice_id=choice)
                    student_response.save()

polls/templates/polls/STAGE1/create_mcq_form.html
<div class="collection-item grey lighten-5">
    {% if student.group == 'G2' %}
    <p class="row">
        This week you mastered …. concepts. Now, we want to give you the opportunity to use your newly acquired
        knowledge and make a useful contribution for future students, that can help them learn better! This
        activity would also encourage the development of your higher-order cognitive skills and lead to a deeper
        understanding of these concepts!
        <br><br>
        Thus, in part 2 of this assignment, you have to create an MCQ supported by an explanation of how to
        arrive at the correct answer. If you consent, we would also like to include the created MCQ for future
        question banks or assessments.
    </p>
    {% endif %}
    <p class="row">
        Create a Multiple choice question with one correct answer and 3 incorrect options. Please select 1 or more
        topics from the list on the right to create your MCQ. You just answered 6 MCQs which are all good examples
        of multiple-choice questions that promote higher-order thinking. All of them have the following features,
        which you should keep in mind while creating your MCQ:<br>
        <ol>
            <li>
                The question should be very clear, and not likely to be ambiguous.
            </li>
            <li>
                There must be only one correct answer.
            </li>
            <li>
                All 3 incorrect options should be plausible. If an option is obviously wrong for all the students,
                then it is not a good option. A good incorrect option should be plausible to a student who has not
                yet learned the skill or knowledge that the MCQ is trying to assess.
            </li>
            <li>
                Your MCQ should require the students to think more than simply repeating memorized facts.
                Higher-order thinking requires students to do something with the facts: apply them, analyze them,
                organize them, align them to concepts and connect to other concepts, question and critique them, and
                use them to creatively solve problems.
            </li>
        </ol>
    </p>
    <p class="row">
        Finally, in 1-2 sentences, explain why the option indicated by you as correct is indeed the correct answer.
        If required, you may also explain why the other options do not qualify as correct answers.
    </p>
    <p class="row">
        <strong>Grading:</strong> This exercise is worth 4 pts with the following break up:<br>
        Question: 1.5 pt<br>
        Correct answer: 0.75 pt<br>
        Three incorrect options: 1 pt<br>
        Explanation: 0.75 pt
    </p>

    <div class="input-field row">
        <select multiple name="topics" required>
            <option value="" disabled>Topics:</option>
            {% for topic in topics %}
                <option value="{{ topic.id }}">{{ topic.text }}</option>
            {% endfor %}
        </select>
        <label>Choose topics relevant to your question</label>
    </div>

    <div class="input-field row">
        <textarea class="materialize-textarea log-text tooltipped" id="student_question" name="student_question"
            data-position="bottom" data-tooltip="Make sure that the question is clear and not ambiguous!"
            required></textarea>
        <label for="student_question">Question</label>
        <span class="helper-text">Required</span>
    </div>

    <div class="input-field row">
        <textarea class="materialize-textarea log-text tooltipped" id="student_choice_1" name="student_choice_1"
            data-position="bottom" data-tooltip="Make sure that this is the correct answer!" required></textarea>
        <label for="student_choice_1">Correct Choice</label>
        <span class="helper-text">Required</span>
    </div>

    <div class="input-field row">
        <textarea class="materialize-textarea log-text tooltipped" id="student_choice_2" name="student_choice_2"
            data-position="bottom" data-tooltip="Make sure that this is an incorrect alternative!" required></textarea>
        <label for="student_choice_2">Incorrect Choice 1</label>
        <span class="helper-text">Required</span>
    </div>

    <div class="input-field row">
        <textarea class="materialize-textarea log-text tooltipped" id="student_choice_3" name="student_choice_3"
            data-position="bottom" data-tooltip="Make sure that this is an incorrect alternative!" required></textarea>
        <label for="student_choice_3">Incorrect Choice 2</label>
        <span class="helper-text">Required</span>
    </div>

    <div class="input-field row">
        <textarea class="materialize-textarea log-text tooltipped" id="student_choice_4" name="student_choice_4"
            data-position="bottom" data-tooltip="Make sure that this is an incorrect alternative!" required></textarea>
        <label for="student_choice_4">Incorrect Choice 3</label>
        <span class="helper-text">Required</span>
    </div>

    <div class="input-field row">
        <textarea class="materialize-textarea log-text tooltipped" id="student_explanation" name="student_explanation"
            data-position="bottom" data-tooltip="Your explanation should serve to help any student who is unable to
                answer the MCQ incorrectly." required></textarea>
        <label for="student_explanation">Explanation</label>
        <span class="helper-text">Required</span>
    </div>

    <div class="row">
        <span>Can I use the MCQ created by you for future research studies given that no personal
            identifiers will be stored or linked back to you?</span>
        <p>
            <label>
                <input type="radio" name="consent_create_mcq" value="True" class="with-gap umblue" required>
                <span>
                    <span class="black-text">Yes</span>
                </span>
            </label>
        </p>
        <p>
            <label>
                <input type="radio" name="consent_create_mcq" value="False" class="with-gap umblue" required>
                <span>
                    <span class="black-text">No</span>
                </span>
            </label>
        </p>
    </div>
</div>

polls/templates/polls/STAGE1/create_mcq_form_wrapper.html
<li>
    <div class="collapsible-header log-question" value="create_mcq"><span>Create MCQ</span></div>
    <div class="collapsible-body grey lighten-5">
        {% include "polls/STAGE1/create_mcq_form.html" %}
    </div>
</li>

polls/templates/polls/STAGE1/list_questions_individual.html
{% for question in latest_question_list %}

    <li>
        <div class="collapsible-header log-question" value="{{ question.id }}">Q{{ forloop.counter|add:offset }}</div>
        <div class="collapsible-body grey lighten-5">
            <p class="question-text">{{ question.question_text|safe }}</p>
            {% for choice in question.choice_set.all %}
            <p>
                <label>
                    <input type="radio" name="mcq_{{ question.id }}" id="{{ question.id }}choice{{ forloop.counter }}"
                        value="{{ question.id }},{{ choice.id }}" class="with-gap umblue log-mcq" required>
                    <span class="black-text">{{ choice.choice_text }}</span>
                </label>
            </p>
            {% endfor %}
        </div>
    </li>

{% endfor %}

polls/templates/polls/STAGE1/quiz_dynamic_individual.html
{% extends '../base.html' %}
{% load static %}
{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


{% if latest_question_list %}

<h6 class="row">
    Hello {{ student.name }}!
</h6>
<p class="row">
    {% if student.group == 'G1' %}
    <span>
        Please answer the following multiple-choice questions (MCQs), indicating one correct
        response for each MCQ. Each MCQ is worth 1 point and no points will be deducted for
        incorrect responses. There are 10 MCQs in total.<br><br>
        You will have to answer all the questions to be able to submit the assignment. If you don't
        know the answer to a question, please select the option "I don't know the answer to this
        question" rather than making a random guess.
    </span>
    {% elif student.group == 'G2' %}
    <span>
        This assignment consists of 2 parts, with part 1 consisting of 6 Multiple Choice Questions
        (MCQs) and part 2 consisting of a question-generation problem. You will have to answer all
        the questions to be able to submit the assignment. <br><br>
        In part 1, please answer the MCQs by indicating one correct response for each MCQ. Each MCQ
        is worth 1 point. If you don't know the answer to a question, please select the option "I
        don't know the answer to this question" rather than making a random guess.

    </span>
    {% else %}
    <span>
        This assignment consists of 2 parts, with part 1 consisting of 6 Multiple Choice Questions
        (MCQs) and part 2 consisting of a choice between 4 more MCQs and a question-generation
        problem. You will have to answer all the questions to be able to submit the assignment. <br><br>
        In part 1, please answer the MCQs by indicating one correct response for each MCQ. Each MCQ
        is worth 1 point. If you don't know the answer to a question, please select the option "I
        don't know the answer to this question" rather than making a random guess.

    </span>
    {% endif %}
</p>

<form action="{% url 'polls:submit_quiz' student.id %}" method="post" class="row" id="main-quiz">
    {% csrf_token %}
    <ul class="collapsible" id="questions-list">

        {% include "polls/STAGE1/list_questions_individual.html" with offset="0" %}

        {% if student.group == 'G2' or student.group == 'G5' %}
        {% include "polls/STAGE1/create_mcq_form_wrapper.html" %}
        {% endif %}
    </ul>

    <div id="submit-quiz">
        {% if student.group != 'G3' %}
        {% include "polls/STAGE1/submit-quiz-button.html" %}
        {% endif %}
    </div>
</form>

{% if student.group == 'G3' %}

<p class="row G3-choice" id="G3-choice-div-text">
    This week you learnt about Pandas Series and Dataframes. Now, we want to give you the opportunity to use your
    newly acquired knowledge and make a useful contribution for future students, that can help them learn better!
    This activity would also encourage the development of your higher-order cognitive skills and lead to a deeper
    understanding of these concepts!<br>
    Thus, you have the opportunity to create an MCQ supported by an explanation of how to arrive at the correct
    answer. Alternatively, you can answer 4 more MCQs. If you consent, we would also like to include the created MCQ
    for future question banks or assessments.<br>
    <strong>Please note that you only have the option to make this choice once and after clicking on the activity of
        your choice, your decision would be final.</strong>
</p>

<span class="row" id="G3-choice-div">
    <a class="waves-effect waves-light btn-large umblue col s4 offset-s1 m3 offset-m2 G3-choice" id="G3-answer"
        value="G4">Answer 4 more MCQs</a>
    <a class="waves-effect waves-light btn-large umblue col s4 offset-s2 m3 offset-m2 G3-choice" id="G3-create"
        value="G5">Create new MCQ</a>
</span>
{% endif %}

{% else %}
<p class="flow-text">No quiz is available.</p>
{% endif %}

{% endblock %}

{% block scripts %}
<script src="{% static 'polls/collapsible_questions.js' %}"></script>
{% if student.group == 'G3' %}
<script src="{% static 'polls/group_3_form.js' %}"></script>
{% endif %}
{% endblock %}

polls/templates/polls/STAGE1/submit-quiz-button.html
<button class="btn waves-effect waves-light umblue" type="submit" name="action">Submit quiz</button>